### ISSUE TITLE
App crashes/shows empty list after entering 'valid' but wrong IP/port

### ISSUE THREAD

**Issue by MarcF12** [RUGSoftEng/2018-Hestia-IOS#140]
The PingServer that is used in the UITableViewControllerServerConnect.cs is not timing out correctly and does not check for a valid Hestia server.

**Comment by daangroot** [comment]
I agree with Feiko's recommendation to just do a request (like getDevices) to check if the server exists.

**Comment by Mikmist** [comment]
This should be fixed with https://github.com/RUGSoftEng/2018-Hestia-IOS/pull/141
