### ISSUE TITLE
Speech recognition broken

### ISSUE THREAD

**Issue by MarcF12** [RUGSoftEng/2018-Hestia-IOS#239]
The latest PRs broke speech recognition. There is a null reference exception due to line 81 in SpeechRecognition.cs. . It can be fixed by simply use ""  as argument, but don't know if that's the best fix.

**Comment by Mikmist** [comment]
Has this been fixed?

**Comment by MarcF12** [comment]
I did 052565fa6f6feb0218419dfe41b8f3ed0c8c9960  in response to Daan's comment
